<?php

/**
 * Implements hook_help().
 */
function order_mobile_detect_help($path, $arg) {
  switch ($path) {

    case 'admin/help#order_mobile_detect':
      $output = '';
      $output .= '<h3>' . t('Introduction') . '</h3>';
      $output .= '<p>' . t('Order Mobile Detect module helps a user detect orders placed using mobile(responsive site).');
      $output .= '<h3>' . t('Requirements') . '</h3>';
      $output .= '<h4>' . t('Drupal Commerce') . '</h4>';
      $output .= t('1. You will need to download drupal commerce module from the site <a href="https://www.drupal.org/project/commerce" target= "_blank"> https://www.drupal.org/project/commerce</a>. </br>');
      $output .= t('2. You can download this module using drush command "drush dl commerce" after that do "drush en commerce" to enable the module.');
      $output .= '<h3>' . t('Installation / Configuration') . '</h4>';
      $output .= 'Install as you would normally install a contributed drupal module. See:'
          . ' <a href="https://drupal.org/documentation/install/modules-themes/modules-7" target= "_blank"> https://drupal.org/documentation/install/modules-themes/modules-7</a> '
          . 'for further information.<br/>';
      $output .= '<h3>' . t('Check Data') . '</h3>';
      $output .= 'You can check the orders placed using mobile and the mobile OS related data under <a href="/admin/commerce/orders/mobile-orders" target= "_blank">admin/commerce/orders/mobile-orders</a>';
      return $output;
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function order_mobile_detect_commerce_order_delete($entity) {
  \Drupal::database()->delete('order_mobile_detect')
      ->condition('order_id', $entity->order_id)
      ->execute();
}
